### ISSUE TITLE
How about including heart rate?

### ISSUE THREAD

**Issue by ZehHa** [prakashait9/Healthify#2]
I would like to use the healthify watchface on my Pebble 2 HR. But there is no heart rate display. Do you have any plans to include the heart rate in your watchface?

**Comment by itsluminous** [comment]
It's good idea, I was working on it but then left after Fitbit acquisition.
If lot of people show interest then I will think about it  👍

**Comment by itsluminous** [comment]
Closing as the change does not seem to be much needed now.
